services:
  voidauth: 
    image: voidauth/voidauth:latest
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    volumes:
      - "./config:/app/config"
    environment:
      # Required environment variables, set in .env file
      APP_DOMAIN: ${APP_DOMAIN:?err} # required
      DB_HOST: ${DB_HOST:?err} # required
      DB_PASSWORD: ${DB_PASSWORD:?err} # required
      STORAGE_KEY: ${STORAGE_KEY:?err} # required

      # Not required or has default
      # APP_TITLE: "VoidAuth"
      # APP_PORT: "3000"
      # APP_COLOR: "#8864c4"
      # SIGNUP: "false"
      # SIGNUP_REQUIRES_APPROVAL: "true"
      # EMAIL_VERIFICATION: "false"
      # DB_PORT: "5432"
      # DB_USER: "postgres"
      # DB_NAME: "postgres"
      # STORAGE_KEY_SECONDARY: 
      # ZXCVBN_MIN: "3"
      # SMTP_HOST: 
      # SMTP_FROM: 
      # SMTP_PORT: "587"
      # SMTP_SECURE: "false"
      # SMTP_USER: 
      # SMTP_PASS: 
    depends_on:
      - voidauth-db

  voidauth-db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: unless-stopped
